<%@ include file="common.jsp" %>
<html>
<head>
  <title>Application Error</title>
  <%@ include file="stylesheet.html" %>
</head>

<body>
  <!-- Output generated by JSP page: src/com/modeln/build/ctrl/view/default/error.jsp -->

  <table border="0" width="100%">

    <tr>
      <td align="left">
        <p>
          <center>The application has experienced an error.</center>
<%  if (error != null) { %>
        <table border="0" cellspacing="0" cellpadding="2" width="90%" align="center">
          <tr>
            <td valign="top" align="right"><b>Error:</b></td>
            <td valign="top" align="left"><%= error.getErrorCode() %>: <%= error.getErrorMsg() %></td>
          </tr>
<%      if (error.getDebugName() != null) { %>
          <tr>
            <td valign="top" align="right"><b>Debug:</b></td>
            <td valign="top" align="left"><%= error.getDebugName() %>: <%= error.getDebugMsg() %></td>
          </tr>
<%      } %>
<%      if (error.getException() != null) { %>
          <tr>
            <td valign="top" align="right"><b>Exception:</b></td>
            <td valign="top" align="left"><code><%= ApplicationException.getStackTrace(error.getException()) %></code></td>
          </tr>
<%      } %>

        </table>
<%  } else { %>
        <center><b>No error found.</b></center>
<%  } %>
        </p>

      </td>
    </tr>
  </table>

</body>
</html>
